name: Fetch BGG Collection

on:
  schedule:
    - cron: "0 6 * * *"   # daily at 6 AM UTC
  workflow_dispatch:

jobs:
  fetch-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch BGG Data with Stats
        run: |
          curl -s "https://boardgamegeek.com/xmlapi2/collection?username=sportomax&own=1&stats=1" -o collection.xml

      - name: Commit and Push Result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add collection.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update collection $(date)"
          git push
