# File: .github/workflows/generate_html_index.yml

name: Generate HTML Index

# Ensure the workflow token has write access globally
permissions: 
  contents: write 
  
# Runs every 4 hours, or manually
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: python -m pip install --upgrade pip
        
    # Step 1: Run the Python script to generate the HTML file
    # This creates or overwrites myhtml.html
    - name: Run HTML index generation script
      run: python generate_index.py
      
    # Step 2: Commit and Push the generated file using the reliable method
    - name: Commit and Push myhtml.html
      run: |
        # 1. Configure Git identity
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # 2. Stage the file (this handles creation and modification)
        git add myhtml.html
        
        # 3. Attempt to commit. The '|| echo "..."' is CRUCIAL 
        #    as it prevents the step from failing if there are no changes 
        #    (the error you were seeing previously).
        git commit -m "🤖 CI: Recreate myhtml.html index" || echo "No changes to commit or file already committed."
        
        # 4. Push the changes
        git push
