# File: .github/workflows/generate_html_index.yml

name: Generate HTML Index

# Ensure the workflow token has write access globally to avoid commit failures
permissions: 
  contents: write 
  pull-requests: write # Added for robust permission handling

# This schedule runs every 4 hours.
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    # Step 3: Install dependencies
    - name: Install dependencies
      run: python -m pip install --upgrade pip
        
    # Step 4: Run the Python script to generate the HTML file
    - name: Run HTML index generation script
      run: python generate_index.py
      
    # ------------------------------------------------------------------
    # NEW STEP: MANUAL COMMIT AND PUSH
    # ------------------------------------------------------------------
    - name: Commit and Push myhtml.html
      run: |
        # Configure the Git user (required for commits)
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Check if the file has changed (non-zero exit code if changes exist)
        # The '|| true' ensures the step doesn't fail if the file is new/modified
        if git diff --exit-code myhtml.html > /dev/null; then
          echo "myhtml.html is unchanged. Skipping commit."
        else
          echo "Changes detected in myhtml.html. Committing..."
          git add myhtml.html
          git commit -m "🤖 CI: Recreate myhtml.html index"
          
          # Push the committed changes back to the origin branch (e.g., 'main')
          git push
        fi
