# File: .github/workflows/generate_html_index.yml

name: Generate HTML Index

# This schedule runs every 4 hours.
# '0' is the minute, '*/4' is the hour (every 4th hour), '*' for day/month/day-of-week
on:
  schedule:
    # Runs at minute 0 past every 4th hour (e.g., 00:00, 04:00, 08:00, 12:00, 16:00, 20:00 UTC)
    - cron: '0 */4 * * *'
  
  # Also allow manual running from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Use a standard GitHub-hosted runner
    runs-on: ubuntu-latest
    
    # Permissions are required to check out the code and push the changes back
    permissions:
      contents: write
      
    steps:
    
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    # Step 3: Install dependencies (optional, but good practice if the script was complex)
    # The current script only uses built-in modules (os, glob, pathlib), so this is minimal
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other required packages here if your script was more complex
        
    # Step 4: Run the Python script to generate the HTML file
    - name: Run HTML index generation script
      run: python generate_index.py
      
    # Step 5: Check if the file was modified
    - name: Check for modified files
      id: git-check
      run: |
        # Check if 'myhtml.html' is different from the version in the repo
        if git diff --exit-code myhtml.html; then
          echo "html_changed=false" >> $GITHUB_OUTPUT
        else
          echo "html_changed=true" >> $GITHUB_OUTPUT
        fi
        
    # Step 6: Commit and push the generated file if it changed
    - name: Commit and Push changes
      if: steps.git-check.outputs.html_changed == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # Commit message for the bot
        commit_message: "🤖 CI: Recreate myhtml.html index"
        # The file to commit
        files: myhtml.html
        # The bot name and email
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions[bot]@users.noreply.github.com
