# This 'name' is what you see in the GitHub Actions tab.
name: Generate HTML Index

# This sets permissions for the GITHUB_TOKEN
permissions: 
  contents: write 

# This 'on' block defines when the action runs
on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  
  # This 'workflow_dispatch' adds the "Run workflow" button
  # in the GitHub Actions tab, allowing you to run it manually.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: python -m pip install --upgrade pip
        
    - name: Run HTML index generation script
      run: python generate_index.py
      
    - name: Commit and Push myhtml.html
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add myhtml.html
        git commit -m "🤖 CI: Recreate myhtml.html index" || echo "No changes to commit."
        git push
