name: Deploy BGG Fetcher

on:
  push:
    branches:
      - main  # Set this to your primary branch (e.g., main or master)
  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Token Injection Step ---
      - name: Inject BGG API Token into index.html
        # IMPORTANT: The secret named 'BGG_API_TOKEN' is now referenced here.
        env:
          BGG_SECRET: ${{ secrets.BGG_API_TOKEN }}
        run: |
          if [ -z "$BGG_SECRET" ]; then
            # Changed error message to reflect the new secret name
            echo "::warning::GitHub Secret 'BGG_API_TOKEN' is not set. Placeholder will remain in index.html."
            # The code handles this case by failing the 'injected' test.
          else
            # Replaces the placeholder string with the actual quoted secret value.
            sed -i "s|GITHUB_SECRET_PLACEHOLDER_TOKEN|\'$BGG_SECRET\'|g" index.html
            echo "Token successfully injected into index.html."
          fi
          
      # --- Deployment Step ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Use the default GitHub token for deployment permissions
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Deploy the root directory (where index.html now lives with the injected secret)
          publish_dir: ./
